version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-playground-db
    environment:
      POSTGRES_DB: ai_playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-playground-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-playground-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_playground
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ai-playground-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-playground-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ai-playground-network

volumes:
  postgres_data:

networks:
  ai-playground-network:
    driver: bridge
